window.comment =
    "Taurasi": "Spicy red wine with a tar and leather feel",
    "Pigato": "A dry white wine with peach flavors",
    "Viognier": "Dry white wine with peach and apricot flavor",
    "Brunello di Montalcino": "A smooth red wine with flavors of chestnuts, plum, and earth",
    "Bourgueil": "From the Loire Valley, a crisp wine with red berry, soft fruit and dusty earth",
    "Barolo": "A dry red wine from Piedmont Italy with dark fruit, licorice, tobacco, smoke and oak",
    "Albarino": "Creamy white wine with peach, honeysuckle, lime and vanilla flavors",
    "Champagne": "A sweet, light, sparkling wine that is refreshing and food-friendly",
    "Zweigelt": "Light red wine with flavors of soft red fruit",
    "Hermitage": "Red wine with black currants, plums, and spice",
    "Olaszrizling": "A dry wine with almond flavor & a green splash",
    "Verdicchio": "Dry, bitter white wine with flavors of almond, apple, and honey with thyme and sage",
    "Tempranillo": "Red wine with tart berries and plum with oak",
    "Madeira": "Sweet wine with caramel, almonds, & hazelnuts",
    "Petite Sirah": "A spicy red wine with plum, cherry, & prunes",
    "Sherry": "A rich wine that smells and tastes of raisins, walnuts, & caramel",
    "Riesling": "Semi-sweet white wine with peach and citrus notes",
    "Cinque Terre": "Crisp white wine with mineral notes, citrus and tart apple flavors",
    "Syrah": "Red wine with blackberry, plum, and jamminess",
    "Soave": "Light, dry, white wine with citrus aromas and lemon-lime, green apple flavors",
    "Pinot Blanc": "A white wine with flavors of apple and pears",
    "Pinot Gris": "A light white wine with crisp citrus flavor",
    "Baga": "A rustic red wine with spice, dark fruits and a hint of mushrooms",
    "Montepulciano": "A smooth wine with dark berry, & pepper",
    "Bandol Rose": "A light rose wine with orange blossom aromas, with strawberry and spice flavors",
    "Barbaresco": "A dry red wine with flavors of cherry, raspberry, and plum",
    "Tawny Port": "A sweet wine with baking spice, almond, & caramel",
    "Beaujolais": "Light red wine with cranberry, strawberry, smoke, and pepper",
    "Grenache": "Red wine which is spicy with black cherry, raspberry, and cinnamon notes",
    "Pouilly-Fuisse": "Dry white wine with a flinty taste and nutty aroma",
    "Rioja": "A spicy Tempranillo-based wine with faint blackberry, black cherry, and red currant",
    "Sangiovese": "Red wine with tart cherry, plum, and spice flavors",
    "Zinfandel": "Red wine with notes of blueberry and blackberry",
    "Gewurztraminer": "Dry, semi-sweet aromatic white wine with a tangerine, white peach smell and lychee flavor",
    "Cotes du Rhone": "Spicy red wine with flavors of raspberries, spice, and vanilla",
    "Asti Spumanti": "A fresh, peachy Northern Italian sparkler with a hint of grapey sweetness",
    "Chardonnay": "A ripe and crisp wine with fruit flavors such as apple, pear, and citrus",
    "Malbec": "A red wine with blackberry, mocha, & spice",
    "Meritage": "Red tannic and austere wine with notes of earth, cedar, and blackcurrant",
    "Tokaji": "Sweet wine with dried raisins, cocoa, spice, & coffee",
    "Nebbiolo": "A red wine with wild cherry, truffles, and tar",
    "Bardolino": "A Northeast Italian dry red wine with aromas and flavors of raspberry",
    "Garnacha": "A red wine with pepper mixed with jammy flavor",
    "Brouilly": "A fruity red wine with flavors of red fruits and black currant",
    "Syrah/Shiraz": "Red wine with blackberry, plum, and jamminess",
    "Carmenere": "Firm red wine with cherry, raspberry, plum, and black pepper with green herbs",
    "Vinho Verde": "A zesty red wine with citrus flavor",
    "Primitivo": "Red wine with some earth, spice, and plum flavors",
    "Valpolicella": "A red wine with black cherry, raisin, & licorice",
    "White Bordeaux Blend": "A sweet white wine blend with creamy texture and flavors of honey and apricot",
    "Red Bordeaux Blend": "A robust, full-bodied red wine blend with black currant, spice, and cedar",
    "Merlot": "Lush red wine with notes of plum, black cherry, and caramel",
    "Rose": "Fruity pink wine with flavors of strawberry, watermelon, and cherry",
    "Sauternes": "A sweet, creamy wine with honey, vanilla, & fruit",
    "Chinon": "A light red wine with berry flavors such as cassis and raspberries",
    "Chablis": "Dry white wine with lemon and pepper balanced by vanilla, pineapple, and spicy oak",
    "Blaufrankisch": "A dry red wine with black & red berries, licorice & spice",
    "Banyuls": "Sweet but not syrupy French dessert wine with espresso, plums, and mocha",
    "Ruby Port": "Sweet red wine with powerful fruit like plum, cherry, & berries",
    "Chenin Blanc": "A sweet white wine with flavors of honey and nectar, with a creamy finish",
    "Prosecco": "Sparkling white wine that is slightly bitter with flavors of golden apple and peach",
    "Aglianico": "A fruit-forward red wine with plum, blackberry, chocolate, and velvety tannins",
    "Chambourcin": "A red wine with flavors of cherry, stone fruit, bubblegum, and spice",
    "Pinot Grigio": "A light white wine with crisp citrus flavor",
    "Blanc de Blanc": "A dry and zesty white sparkling wine with flavors of peach & apricot",
    "Cabernet Sauvignon": "A rich, dry red wine with black fruit, oak and pepper",
    "Haut-Medoc": "A mild red wine with vanilla & black fruits",
    "Barsac": "A honey-sweet wine with flavors of vanilla and dried fig",
    "Chateauneuf-du-Pape": "Spicy red wine with ripe flavors of black fruit, coffee, and pepper",
    "Gamay": "Light red wine with flavors of strawberry and cherry",
    "Viognier": "Dry white wine with peach and apricot flavors",
    "Pinot Noir": "Light to medium-bodied, food friendly red wine with red berry and cherry flavors",
    "Sauvignon Blanc": "A grassy white wine with herbs & smoke",
    "Cabernet Franc": "A smooth red wine with berry flavor, green herbs, bell pepper and dark earth",
    "Chianti": "A spicy red wine with red cherry and pepper flavors from the Tuscany region of Italy",
    "Gruner Veltliner": "Dry white wine with flavors of lemon-lime, grapefruit, arugula, and pepper",
    "Marsanne": "Waxy white wine with flavors of almonds and citrus",
    "Dolcetto": "Jammy red wine with flavors of cherry",
    "Moscato": "Sweet white wine",
    "Bandol": "Spicy red wine with cinnamon and vanilla mixed with black fruits",
    "Barbera": "Acidic, juicy red wine with flavors of black cherry",
    "Vouvray": "A wine with flavors of pear, fig, apple, & honey",
    "Sparkling Rose wine": "A fruity pink wine with flavors of wild strawberry, watermelon & cherry",
    "White Zinfandel": "Juicy wine prepared like a white wine with citrus and berry flavors"
