window.pronounce =
  "Taurasi": "tow-RAH-zee"
  "Pigato": "pee-GAH-toh"
  "Viognier": "veeh-oh-NYAY"
  "Brunello di Montalcino": "broo-NELL-oh"
  "Bourgueil": "boor-GEUH-yuh"
  "Barolo": "bah-ROH-loh"
  "Albarino": "ahl-bah-REE-nyoh"
  "Amarone": "None"
  "Port": "None"
  "Champagne": "sham-PAYN"
  "Zweigelt": "TSVYE-gelt"
  "Hermitage": "ehr-mee-TAHZH"
  "Olaszrizling": "OL-AHS-REES-LING"
  "Verdicchio": "vehr-DEEK-kyoh"
  "Tempranillo": "tem-prah-NEE-yoh"
  "Red Burgundy": "None"
  "Madeira": "muh-DEER-uh"
  "Petite Sirah": "peh-TEET sih-RAH"
  "Sherry": "A rich wine that smells and tastes of raisins, walnuts, & caramel"
  "Riesling": "REEZ-ling"
  "Cinque Terre": "CHEEN-quay TAIR-ay"
  "Syrah": "see-RAH"
  "Soave": "SWAH-vay"
  "Pinot Blanc": "PEE-noh BLAHNGK"
  "Pinot Gris": "PEE-noh GREE"
  "Baga": "BAH-guh"
  "Montepulciano": "Mon-teh-pool-CHAH-no"
  "Bandol Rose": "bahn-DAWL roh-ZAY"
  "Barbaresco": "bar-bah-RESS-koh"
  "Tawny Port": "A sweet wine with baking spice, almond, & caramel"
  "Beaujolais": "boh-zhuh-LAY"
  "Grenache": "gruh-NAHSH"
  "Pouilly-Fuisse": "poo-yee FWEE-SAY"
  "Rioja": "ree-OH-hah"
  "Sangiovese": "san-joh-VAY-zeh"
  "Zinfandel": "ZIHN-fuhn-dehl"
  "Gewurztraminer": "guh-VURTS-trah-mee-ner"
  "Cotes du Rhone": "koht dea ROHN"
  "Asti Spumanti": "AH-stee spoo-MAH-tee"
  "Chardonnay": "shar-doh-NAY"
  "Malbec": "mahl-BEHK"
  "Meritage": "MEH-rih-TIJ"
  "Tokaji": "toh-KAY"
  "Nebbiolo": "neh-be-YOH-lo"
  "Bardolino": "bar-doh-LEE-noh"
  "Garnacha": "gar-NAR-cha"
  "Brouilly": "broo-YEE"
  "Syrah/Shiraz": "see-RAH"
  "Carmenere": "kahr-meh-NEHR"
  "Vinho Verde": "VEE-nyoh VEHR-deh"
  "Primitivo": "pree-mee-TEE-voh"
  "Valpolicella": "vahl-paw-lee-CHEHL-lah"
  "White Bordeaux Blend": "bohr-DOH"
  "Red Bordeaux Blend": "bohr-DOH"
  "Merlot": "mer-LOH"
  "Rose": "roh-ZAY"
  "Sauternes": "soh-TEHRN"
  "Chinon": "shee-NOHN"
  "Chablis": "sha-BLEE"
  "Blaufrankisch": "blouw-FRAHN-keesh"
  "Banyuls": "bah-NYUHLS"
  "Ruby Port": "Sweet red wine with powerful fruit like plum, cherry, & berries"
  "Burgundy": "None"
  "Chenin Blanc": "SHEN-ihn BLAHNGK"
  "Prosecco": "proh-SEHK-koh"
  "Aglianico": "ah-LYAH-nee-koh"
  "Chambourcin": "shahm-boor-SAN"
  "Pinot Grigio": "PEE-noh GREE-geo"
  "Blanc de Blanc": "BLAHNGK duh BLAHNGK"
  "Cabernet Sauvignon": "ka-behr-NAY soh-vihn-YOHN"
  "Haut-Medoc": "oh may-DAHK"
  "Barsac": "BAHR-sak"
  "Chateauneuf-du-Pape": "sha-toh-nuhf-doo-PAHP"
  "Gamay": "ga-MAY"
  "Viognier": "vee-oh-NYAY"
  "Pinot Noir": "PEE-noh NWAHR"
  "brut Champagne": "None"
  "Sauvignon Blanc": "SOH-vee-nyawn BLAHNGK"
  "Cabernet Franc": "KA-behr-nay FRAHNK"
  "Chianti": "kee-AHN-tee"
  "Gruner Veltliner": "GROO-ner FELT-lih-ner"
  "Marsanne": "mahr-SAN"
  "Dolcetto": "dohl-CHEHT-oh"
  "Moscato": "MUH-skat-OH"
  "Corton-Charlemagne": "None"
  "Bandol": "bahn-DAWL"
  "Barbera": "bar-BEH-rah"
  "Vouvray": "voo-VRAY"
  "Sparkling Rose wine": "roh-ZAY"
  "White Zinfandel": "ZIHN-fuhn-dehl"
