// Generated by CoffeeScript 1.6.2
(function() {
  var prettyDate, toSeconds;

  window.hyphenate = function(str) {
    return str.replace(/[\ \.\']/g, '-');
  };

  toSeconds = function(date) {
    return (new Date(date)).valueOf();
  };

  prettyDate = function(date) {
    return (new Date(date)).toLocaleDateString();
  };

  Handlebars.registerHelper("hyphenate", hyphenate);

  Handlebars.registerHelper("toSeconds", toSeconds);

  Handlebars.registerHelper("prettyDate", prettyDate);

}).call(this);
