// Generated by CoffeeScript 1.6.2
(function() {
  var hyphenate, toSeconds;

  hyphenate = function(str) {
    return str.split(" ").join("-");
  };

  toSeconds = function(date) {
    return (new Date(date)).valueOf();
  };

  Handlebars.registerHelper("hyphenate", hyphenate);

  Handlebars.registerHelper("toSeconds", toSeconds);

}).call(this);
