// Generated by CoffeeScript 1.6.2
(function() {
  ({
    hyphenate: function(str) {
      return str.split(" ").join("-");
    }
  });

  Handlebars.registerHelper("hyphenate", hyphenate);

}).call(this);
