// Generated by IcedCoffeeScript 1.4.0c
(function() {
  var iced, __iced_k, __iced_k_noop,
    __slice = [].slice;

  iced = {
    Deferrals: (function() {

      function _Class(_arg) {
        this.continuation = _arg;
        this.count = 1;
        this.ret = null;
      }

      _Class.prototype._fulfill = function() {
        if (!--this.count) return this.continuation(this.ret);
      };

      _Class.prototype.defer = function(defer_params) {
        var _this = this;
        ++this.count;
        return function() {
          var inner_params, _ref;
          inner_params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          if (defer_params != null) {
            if ((_ref = defer_params.assign_fn) != null) {
              _ref.apply(null, inner_params);
            }
          }
          return _this._fulfill();
        };
      };

      return _Class;

    })(),
    findDeferral: function() {
      return null;
    },
    trampoline: function(_fn) {
      return _fn();
    }
  };
  __iced_k = __iced_k_noop = function() {};

  $(function() {
    var refreshCellars;
    refreshCellars = function() {
      var cellars, html, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/Users/zgrannan/Dropbox/cse110/Frontend/coffee/managecellars.iced",
          funcname: "refreshCellars"
        });
        backend.Cellar.get({
          owner_id: backend.userId
        }, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return cellars = arguments[0];
            };
          })(),
          lineno: 3
        }));
        __iced_deferrals._fulfill();
      })(function() {
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/zgrannan/Dropbox/cse110/Frontend/coffee/managecellars.iced",
            funcname: "refreshCellars"
          });
          frontend.renderTemplate("manage_cellars_table", {
            cellars: cellars
          }, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return html = arguments[0];
              };
            })(),
            lineno: 4
          }));
          __iced_deferrals._fulfill();
        })(function() {
          $("#cellars-table-body").html(html);
          return $(".editcellar-button").click(function() {
            return window.selectedCellar = parseInt($(this).data("cellar-id"));
          });
        });
      });
    };
    $("#create-cellar-button").click(function(event) {
      var name, nothing, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      event.preventDefault();
      name = $("#create-cellar-name").val();
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/Users/zgrannan/Dropbox/cse110/Frontend/coffee/managecellars.iced"
        });
        backend.Cellar.create({
          owner: backend.profileUri,
          name: name
        }, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return nothing = arguments[0];
            };
          })(),
          lineno: 12
        }));
        __iced_deferrals._fulfill();
      })(function() {
        return refreshCellars();
      });
    });
    $("#deleteconfirm").click(function(event) {
      var nothing, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      event.preventDefault();
      if ($("#deletetext").val().trim() === "DELETE") {
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/zgrannan/Dropbox/cse110/Frontend/coffee/managecellars.iced"
          });
          backend.Cellar["delete"](window.selectedCellar, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return nothing = arguments[0];
              };
            })(),
            lineno: 18
          }));
          __iced_deferrals._fulfill();
        })(function() {
          refreshCellars();
          return __iced_k($("#deletecellar").modal("hide"));
        });
      } else {
        return __iced_k($("#deletetext").valerror());
      }
    });
    $("#save-cellar").click(function(event) {
      var cellarName, nothing, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      cellarName = $("#cellarname").val();
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/Users/zgrannan/Dropbox/cse110/Frontend/coffee/managecellars.iced"
        });
        backend.Cellar.update(window.selectedCellar, {
          name: cellarName
        }, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return nothing = arguments[0];
            };
          })(),
          lineno: 26
        }));
        __iced_deferrals._fulfill();
      })(function() {
        return refreshCellars();
      });
    });
    return refreshCellars();
  });

}).call(this);
