// Generated by IcedCoffeeScript 1.4.0c
(function() {

  window.Util = {
    byId: function(obj) {
      return obj.id;
    },
    flatMap: function(list, fn) {
      return _.reject(_.map(list, fn), function(elem) {
        return !elem;
      });
    }
  };

}).call(this);
